extends:
  - plugin:@mysticatea/es2015
  - plugin:@mysticatea/+node

overrides:
  - files: "typings/**"
    rules:
      node/no-missing-import:
        - error
        - allowModules:
          - estree

settings:
  node:
    tryExtensions:
      - .ts
      - .js
      - .json
